{
  "comments": [
    {
      "key": {
        "uuid": "ad9ca8e3_2fadf95f",
        "filename": "dci_downloader/api.py",
        "patchSetId": 1
      },
      "lineNbr": 25,
      "author": {
        "id": 28
      },
      "writtenOn": "2020-11-03T15:55:00Z",
      "side": 1,
      "message": "What if there\u0027s another error ???\n\nShould we print some message explaining it anyway ?",
      "revId": "4e97c58ccc893ab890fff4e8e8c2799e2066ef13",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0",
      "unresolved": false
    }
  ]
}